//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Babyworld.store
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EcommerceProjectDBEntities : DbContext
    {
        public EcommerceProjectDBEntities()
            : base("name=EcommerceProjectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbladmin> tbladmins { get; set; }
        public DbSet<tblbrand> tblbrands { get; set; }
        public DbSet<tblcustomer> tblcustomers { get; set; }
        public DbSet<tblproduct> tblproducts { get; set; }
        public DbSet<tblshoppingcart> tblshoppingcarts { get; set; }
    
        public virtual ObjectResult<chk_customer_email_Result> chk_customer_email(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<chk_customer_email_Result>("chk_customer_email", emailParameter);
        }
    
        public virtual ObjectResult<chk_email_Result> chk_email(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<chk_email_Result>("chk_email", emailParameter);
        }
    
        public virtual ObjectResult<customershoppingcartdetails_Result> customershoppingcartdetails(Nullable<int> customerid)
        {
            var customeridParameter = customerid.HasValue ?
                new ObjectParameter("customerid", customerid) :
                new ObjectParameter("customerid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<customershoppingcartdetails_Result>("customershoppingcartdetails", customeridParameter);
        }
    
        public virtual int delete_user(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_user", useridParameter);
        }
    
        public virtual int deleteCartProduct(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteCartProduct", idParameter);
        }
    
        public virtual int deleteproduct(Nullable<int> productid)
        {
            var productidParameter = productid.HasValue ?
                new ObjectParameter("productid", productid) :
                new ObjectParameter("productid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteproduct", productidParameter);
        }
    
        public virtual ObjectResult<get_admins_Result> get_admins()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_admins_Result>("get_admins");
        }
    
        public virtual ObjectResult<get_specific_brand_products_Result> get_specific_brand_products(string brandname)
        {
            var brandnameParameter = brandname != null ?
                new ObjectParameter("brandname", brandname) :
                new ObjectParameter("brandname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_specific_brand_products_Result>("get_specific_brand_products", brandnameParameter);
        }
    
        public virtual ObjectResult<getbrands_Result> getbrands()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getbrands_Result>("getbrands");
        }
    
        public virtual ObjectResult<getproductdetails_Result> getproductdetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getproductdetails_Result>("getproductdetails");
        }
    
        public virtual ObjectResult<login_customer_Result> login_customer(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<login_customer_Result>("login_customer", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<login_user_Result> login_user(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<login_user_Result>("login_user", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<shoppingcartdetails_Result> shoppingcartdetails(string visitorid)
        {
            var visitoridParameter = visitorid != null ?
                new ObjectParameter("visitorid", visitorid) :
                new ObjectParameter("visitorid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<shoppingcartdetails_Result>("shoppingcartdetails", visitoridParameter);
        }
    }
}
