//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Babyworld.store
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbrand
    {
        public tblbrand()
        {
            this.tblproducts = new HashSet<tblproduct>();
        }
    
        public int brand_id { get; set; }
        public string brandname { get; set; }
    
        public virtual ICollection<tblproduct> tblproducts { get; set; }
    }
}
