//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Babyworld.store
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcustomer
    {
        public int customerid { get; set; }
        public string customername { get; set; }
        public string password { get; set; }
        public string customeremail { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
