//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Babyworld.store
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblproduct
    {
        public tblproduct()
        {
            this.tblshoppingcarts = new HashSet<tblshoppingcart>();
        }
    
        public int productid { get; set; }
        public string productname { get; set; }
        public string productdesc { get; set; }
        public decimal productprice { get; set; }
        public int productqty { get; set; }
        public string productimage { get; set; }
        public Nullable<int> brand_id { get; set; }
    
        public virtual tblbrand tblbrand { get; set; }
        public virtual ICollection<tblshoppingcart> tblshoppingcarts { get; set; }
    }
}
